// <auto-generated />
namespace OnlineCookbook.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class maja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(maja));
        
        string IMigrationMetadata.Id
        {
            get { return "201507231549171_maja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
